name: CI/CD Pipeline

on:     #Le déclencheur
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:                      #Les jobs à exécuter
  test:
    name: Tests Unitaires
    runs-on: ubuntu-latest     #le Runner
    steps:                            #Les étapes à exécuter dans ce job
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Configuration Python 3.11
        uses: actions/setup-python@v5 # MIS À JOUR
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lancer les tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=app --cov-report=xml
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v4 # MIS À JOUR
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Optionnel selon ton projet
          fail_ci_if_error: false

  code-quality:
    name: Qualité du Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Configuration Python
        uses: actions/setup-python@v5 # MIS À JOUR
        with:
          python-version: '3.11'
      
      - name: Vérification Flake8
        run: |
          pip install flake8
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [test, code-quality]
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Configuration Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: blog-api:latest

  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name:  Simuler le déploiement
        run: echo " Application déployée avec succès!"
